from typing import Protocol
from typing import Optional

class PromptServiceProtocol(Protocol):
    def get_system_prompt(self, question: str, context: Optional[dict]) -> str: ...
    def get_user_prompt(self, question: str, context: Optional[dict]) -> str: ...