from typing import Protocol
from typing import Optional

class TaskProtocol(Protocol):
    def build_system_prompt(self, question: str, context: Optional[dict]) -> str: ...
    def build_user_prompt(self, question: str, context: Optional[dict]) -> str: ...
    def extract_answer(self, response: str) -> str: ...
    def extract_answer_from_ground_truth(self, ground_truth: str) -> str: ...
    def is_correct(self, answer: str, ground_truth: str) -> bool: ...