from typing import Protocol


class TaskProtocol(Protocol):
    def build_prompt(self, question: str) -> str: ...
    def extract_answer(self, response: str) -> str: ...
    def extract_answer_from_ground_truth(self, ground_truth: str) -> str: ...
    def is_correct(self, answer: str, ground_truth: str) -> bool: ...